# Generated by Django 4.2.2 on 2023-10-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_myuser_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
